### ISSUE TITLE
Decide on final name for main extension

### ISSUE THREAD

**Issue by patrickp** [mvextensions/mvbasic#1]
We need to define names for each of the actual extensions.  The entire git repository for all the extensions is mvextensions.  It seemed redundant and not fully clear if we then called the primary extension also mvextensions.  I checked in VSS and mvbasic is not taken.  I have for now renamed this primary extension mvbasic.  This extension has

1. Syntax highlighting
2. Linter
3. File system handler

**Comment by itsxallwater** [comment]
I like mvbasic.

**Comment by itsxallwater** [comment]
So it was written, and so it shall be--welcome to the world, MV Basic!
