### ISSUE TITLE
[BUG] NEXT in FOR/NEXT loop not recognized if preceded by a Label

### ISSUE THREAD

**Issue by brentlblair** [mvextensions/mvbasic#104]
**Describe the bug**
It the text and attached image, the Lint does not see shows a missing NEXT L for the FOR L.  It highlights the error under the NEXT L that is saying is missing.

**To Reproduce**
      FOR P=1 TO NUM.PARTS
        FOR L=1 TO LOC.CNT
          THIS.AVAIL.QTY=PARTS.ARRAY<7,P,L>
          ORDER.QTY=PARTS.ARRAY<5,P>
          IF THIS.AVAIL.QTY >= ORDER.QTY THEN
            PARTS.ARRAY<11,P>=PARTS.ARRAY<8,P,L>
            GOTO 103
          END
        NEXT L
        IF PARTS.ARRAY<11,P>="" THEN GOSUB BACKORDER.LOCATION.CHECK
103
      NEXT P

**Screenshots**
![Code_jWfFWF3H8m](https://user-images.githubusercontent.com/23214321/83435735-bc0fc600-a40a-11ea-9b5d-e9783cd43982.png)

**Comment by kpowick** [comment]
I am unable to reproduce this problem using the code example that you provided.

Which version of the extension are you using?  The latest is 2.0.6.

**Comment by dthiot** [comment]
Brent,

It is likely that it is some of the code before or after the loops that is causing your behavior.  Did you check it with just the snippet that you sent?

Dick

**Comment by brentlblair** [comment]
I am using 2.0.6.  I tried a few other things.  I copied just that portion
of the code to a new program, and there is no error.  In the original
program, I have this similar loop above the code where the error shows.

    NUM.PARTS=DCOUNT(PARTS.ARRAY<1>,VM)
      LOC.CNT=DCOUNT(ROUTE.LOC.ARRRAY<1>,VM)
      FOR P=1 TO NUM.PARTS
        BASE.PN=PARTS.ARRAY<2,P>
        FOR L=1 TO LOC.CNT
          THIS.LOC=ROUTE.LOC.ARRRAY<1,L>
          PARTS.ARRAY<7,P,L>="0"      ;*AVAIL BY SUBVALUED BY LOCATION
          PARTS.ARRAY<8,P,L>=THIS.LOC ;*LOCATION NUMBER
          IF BASE.PN="C" THEN GOTO 102
          CHECK.LOC=THIS.LOC
          CALL GET.PRODUCT.AVAILABILITY.SOE(BASE.PN,AVAIL,CHECK.LOC)
          PARTS.ARRAY<7,P,L>=AVAIL    ;*AVAIL BY SUBVALUED BY LOCATION
102     NEXT L
      NEXT P

If I change the code to this, it works:

      NUM.PARTS=DCOUNT(PARTS.ARRAY<1>,VM)
      LOC.CNT=DCOUNT(ROUTE.LOC.ARRRAY<1>,VM)
      FOR P=1 TO NUM.PARTS
        BASE.PN=PARTS.ARRAY<2,P>
        FOR L=1 TO LOC.CNT
          THIS.LOC=ROUTE.LOC.ARRRAY<1,L>
          PARTS.ARRAY<7,P,L>="0"      ;*AVAIL BY SUBVALUED BY LOCATION
          PARTS.ARRAY<8,P,L>=THIS.LOC ;*LOCATION NUMBER
          IF BASE.PN="C" THEN CONTINUE
          CHECK.LOC=THIS.LOC
          CALL GET.PRODUCT.AVAILABILITY.SOE(BASE.PN,AVAIL,CHECK.LOC)
          PARTS.ARRAY<7,P,L>=AVAIL    ;*AVAIL BY SUBVALUED BY LOCATION
        NEXT L
      NEXT P

It seems it does not like the use of a line number before a NEXT, but it
gets confused on which line the error is actually.  Either way works as
valid code on jBase.  I understand that CONTINUE with no line number is
probably better, but we migrated to jBase from a system that did not have
the CONTINUE verb.  Also there are some cases where there is a loop inside
of a loop, and I need to BREAK from the inner loop, and CONTINUE to the
outer loop.  Sometimes that is just easier with a line number.

*Brent Blair* <http://www.linkedin.com/in/BrentLBlair>

Vice President of IT
Encompass
Phone 954.474.0300
Fort Lauderdale, FL
<https://www.google.com/maps/place/Encompass+Parts+Distribution/@26.145357,-80.2482168,12.46z/data=!4m5!3m4!1s0x0:0xb2bfe23d3412449!8m2!3d26.0920996!4d-80.2409538>

bblair@encompass.com
encompass.com

**Comment by kpowick** [comment]
You are correct that the numbered label preceding the `NEXT` is causing the issue.  We'll have to look into that for the next release.

As you noted, you can use `CONTINUE`, or you can just put the label on a line by itself.

 ```
          CALL GET.PRODUCT.AVAILABILITY.SOE(BASE.PN,AVAIL,CHECK.LOC)
          PARTS.ARRAY<7,P,L>=AVAIL    ;*AVAIL BY SUBVALUED BY LOCATION
102:
        NEXT L
      NEXT P
```

> Also there are some cases where there is a loop inside
> of a loop, and I need to BREAK from the inner loop, and CONTINUE to the
> outer loop.  Sometimes that is just easier with a line number.

I get it, especially when porting a codebase to a different platform.  However, in the case you describe, I would probably set a flag on the inner loop so that if one uses `EXIT or BREAK` to jump out, the outer loop "knows" to `CONTINUE` instead of process.

```
FOR J = 1 TO 10
   IS.COMPLETE = @TRUE
   FOR K = 1 TO 10
      IF {condition} THEN
         IS.COMPLETE = @FALSE
         EXIT
      END
   NEXT K
   IF NOT(IS.COMPLETE) THEN CONTINUE
   {Processing}
NEXT J
```

**Comment by kpowick** [comment]
BTW, I'm working on other aspects for `FOR/NEXT` tracking that allow things like NEXT with no named variable.  So, I'll look into this new problem as well.

Again, thanks for reporting it.
