### ISSUE TITLE
[BUG] For/Next not recognized if no whitespace after FOR variable

### ISSUE THREAD

**Issue by kpowick** [mvextensions/mvbasic#107]
**Describe the bug**
This issue was originally reported by @brentlblair as of release of `v2.0.7`.

A `FOR/NEXT` statement block displays an error if the variable in the `FOR` statement has no whitespace between it and the equal sign.

**To Reproduce**

`FOR X = 1 TO 10` <--OK
`FOR X=1 TO 10`  <-- No whitespace after `X`.  Error displayed by linter

<img width="415" alt="Screen Shot 2020-06-11 at 13 14 19" src="https://user-images.githubusercontent.com/1646753/84418684-82e30d00-abe5-11ea-8482-4997df8b8f53.png">

**Comment by kpowick** [comment]
@itsxallwater  This issue is now resolved on the `develop` branch.  I'll leave it up to you to update `master` and distribute a hotfix.
  
If there is anything I can do to help, please let me know.

**Comment by itsxallwater** [comment]
We need to get you added to the publisher account in Microsoft but last time we did it for some other folks on the team it was kind of a pain. The good news is building and publishing is pretty straight forward once you're there. I've already done that just buttoning up the repo side.

**Comment by kpowick** [comment]
@brentlblair @dthiot  I was able to update the extension to `v2.0.8` via VS Code, and all is working as expected.

**Comment by brentlblair** [comment]
Yes, it looks good to me.  I appreciate the quick turnaround.  I will
let you know if I notice any other false positives.

*Brent Blair* <http://www.linkedin.com/in/BrentLBlair>

Vice President of IT
Encompass
Phone 954.474.0300
Fort Lauderdale, FL
<https://www.google.com/maps/place/Encompass+Parts+Distribution/@26.145357,-80.2482168,12.46z/data=!4m5!3m4!1s0x0:0xb2bfe23d3412449!8m2!3d26.0920996!4d-80.2409538>

bblair@encompass.com
encompass.com
