### ISSUE TITLE
[BUG] Formating comment lines

### ISSUE THREAD

**Issue by brentlblair** [mvextensions/mvbasic#110]
Not sure if this is considered a bug or the intended outcome.  Either way, it's a minor issue.  I noticed that the `format document` also indents the comments lines to the configured code margin.  I think the comment lines should either be ignored or moved to zero margin.  In my opinion, it makes the program harder to read.

This is what I think the formatted document should look like:

![Code_jWPIqwin7S](https://user-images.githubusercontent.com/23214321/84507228-7cf53680-ac8e-11ea-8741-609db02c86a6.png)

This is what the format document looks like today:
![Code_WYBF7daESF](https://user-images.githubusercontent.com/23214321/84507230-7d8dcd00-ac8e-11ea-8f3c-49f7b45321a3.png)

**Comment by kpowick** [comment]
Looking at the code that handles formatting, comment lines _should_ already be ignored.  I use a zero margin in my own user settings, so haven't noticed what you're reporting.

I'll take  a look at what might be causing this "regression".

**Comment by dthiot** [comment]
Could we have a workspace setting that would indent comments to the level of the associated code, left justified or to a comment margin which would likely be set to 0?  This might require two settings if comment margin is an option.

**Comment by kpowick** [comment]
@dthiot  That's an interesting idea.  If it's something you would like to see, would you please enter it as a new enhancement request?  Otherwise, it may get lost in the comments thread of this issue.

**Comment by dthiot** [comment]
I’m happy to create the enhancement request.  I just thought I would float the idea first for discussion.  I’ll create the request.

**Comment by kpowick** [comment]
Thanks, @dthiot !

I get what you're saying and hope I didn't give the impression that I was trying to dismiss your idea or put you off.  It makes sense to ask, right?  Why bother creating a new request if nobody is really interested?

I was just trying to preemptively keep the comments on this issue from drifting into a discussion not specifically on topic for it.  For example, participants agree that your idea is a good one, then start discussing how it should be implemented, options available, naming conventions, etc.

**Comment by pschellenbach** [comment]
While on the issue of formatting comments, wED has two comment settings: one for '*' comments and one for '!' comments. Each can be set to indent none, margin or code level. No special formatting is provided for REM statements.

**Comment by kpowick** [comment]
@brentlblair  This issue is resolved.  Comment lines are now ignored when it comes to indentation.  This actually used to be the case, and I'm still trying to figure out where this "regression" crept in.

Maybe @itsxallwater can produce a hotfix for this?  I'm not sure if an entirely new release is needed.  I suppose I should figure out how to build a VSIX file.

**Comment by itsxallwater** [comment]
I think I'd like this feature toggled to be honest. I tend to keep comments indented with code. I could be in the minority (or alone altogether) but this feels like the kind of thing that we'd be better served to make an option.

**Comment by itsxallwater** [comment]
Re: building a vsix I've got you covered @kpowick! Check this: https://github.com/mvextensions/mvbasic/issues/96#issuecomment-624794621

**Comment by brentlblair** [comment]
I agree with making this a setting.  You will never get everyone to agree
on a coding style.  I forgot that WED had the 3 settings for comments.  I
think the default is no indent, so that's what I have always used.

*Brent Blair* <http://www.linkedin.com/in/BrentLBlair>

Vice President of IT
Encompass
Phone 954.474.0300
Fort Lauderdale, FL
<https://www.google.com/maps/place/Encompass+Parts+Distribution/@26.145357,-80.2482168,12.46z/data=!4m5!3m4!1s0x0:0xb2bfe23d3412449!8m2!3d26.0920996!4d-80.2409538>

bblair@encompass.com
encompass.com

**Comment by dthiot** [comment]
I like Pete’s suggestion of the way that he does it on Accuterm in terms of none, margin or code.  I think that margin is the standard indent margin, right?  That means only one workspace parameter required.

**Comment by kpowick** [comment]
@itsxallwater I like my comments aligned with code as well, and the latest commit to `develop` does not change your comment indentation, which was the problem seen by @brentlblair .

**Comment by dthiot** [comment]
Feature request submitted.  Please feel free to modify.  I have suggested 4 options instead of Pete’s 3.  None means that comments are left in place.  Left means that comments are moved to the left edge.  Margin and code remain the same as Accuterm.

**Comment by kpowick** [comment]
> Re: building a vsix I've got you covered @kpowick! Check this: [#96 (comment)](https://github.com/mvextensions/mvbasic/issues/96#issuecomment-624794621)

@itsxallwater Thanks for that.  I've got a vsix for the extension (still at 2.0.8) that @brentlblair can use to update his extension.  Two questions:

1) Should I have changed the version number for this vsix "hotfix"?  It's still 2.0.8

2) Where can I make this vsix file available?  I have an on-line storage provider from which I can create a download link.

**Comment by itsxallwater** [comment]
You can attach files here in your comment. I've found that's become the most handy, the link is shareable beyond just the comment and it keeps things close to home. Now that the vsix is tiny it works well!

**Comment by kpowick** [comment]
@brentlblair Attached is a vsix file for a patched version of the extension 2.0.8.

**To Install**

1. Download the attached zip file and extract the file `mvbasic-2.0.8.patched.vsix`
2. Open VS Code
3. Open the Command Palette `cmd+shift+P` or `menu/view/Command Palette`
4. Type `vsix` to find the option `Extensions: Install from VSIX...`
5. Select that option.
6. From the file dialogue that opens, select the file `mvbasic-2.0.8.patched.vsix` and click on the "install" button.

You'll have to do a document reload for the change to take effect.

Please let me know how it goes.

[mvbasic-2.0.8.patched.zip](https://github.com/mvextensions/mvbasic/files/4772242/mvbasic-2.0.8.patched.zip)

**Comment by kpowick** [comment]
> Edit: regarding the version number, yeah ideally you'd bump it up apologies for that.

Didn't see your edit until after posting the vsix.  As the formatting option was the only change, it's probably ok just to leave it as is for now, don't you think?

**Comment by brentlblair** [comment]
Thank you, it works great.

*Brent Blair* <http://www.linkedin.com/in/BrentLBlair>

Vice President of IT
Encompass
Phone 954.474.0300
Fort Lauderdale, FL
<https://www.google.com/maps/place/Encompass+Parts+Distribution/@26.145357,-80.2482168,12.46z/data=!4m5!3m4!1s0x0:0xb2bfe23d3412449!8m2!3d26.0920996!4d-80.2409538>

bblair@encompass.com
encompass.com

**Comment by itsxallwater** [comment]
2.0.9 released! Closing issue.
