### ISSUE TITLE
[FEATURE] Linter Context for MV Subroutines and Functions

### ISSUE THREAD

**Issue by brentlblair** [mvextensions/mvbasic#113]
I know the linter has custom text for jBase VERBS that shows how to use the VERB.  I would like to enhance this by being able to describe SOME frequently used Subroutines and Functions from my system possibly using the MVBasic settings file in json format.

Something like this could be added to the MVBasic settings:
```
"MVBasic.CustomFunctions":[
  {
    "Name":"DateTimeFormat",
    "Values":"inDate,inTime,'format'",
    "Notes":"Format internal data and or time in custom external format|You must have INCLUDE BP CustomLibrary in any program that refreences this function|inDate=date in internal format - can be null if you do not need to convert date|inTime=time in internal format - can be null if you do not need to convert time|format=string using any combination of the follow characters, undefinded characters will be used as literals"
  }
],
```
The above code would auto complete the following in VS Code:
`DateTimeFormat(inDate,inTime,'format')`

It would also display the following hover / help text (I used a | to indicate a new line:
```
Format internal data and or time in custom external format
You must have INCLUDE BP CustomLibrary in any program that refreences this function
inDate=date in internal format - can be null if you do not need to convert date
inTime=time in internal format - can be null if you do not need to convert time
format=string using any combination of the follow characters, undefinded characters will be used as literals
```
Please let me know if this makes sense of if you have any questions.

**Comment by ianmcgowan** [comment]
Brent, this seems like an excellent candidate for "[User Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets)".  I have the following in mine, as well as common things like OPEN, READ, WRITE, defined the way I like them.  When I type SUB, hit Ctrl-Space for complete, and choose the SUB snippet, I can tab through the various completions to fill in $1, $2, etc in the snippet body.

![Snippet](https://user-images.githubusercontent.com/408975/85485245-2d134b00-b57d-11ea-9300-fc37b3220440.gif)


```
{
  "SUBROUTINE Skeleton": {
    "prefix": "SUB",
    "body": [
      "SUBROUTINE $1($2)",
      "***************************************************************************",
      "* Program: $1",
      "* Author : Ian McGowan",
      "* Created: ${3:$CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE}",
      "* Updated: $3",
      "* Comment: $4",
      "***************************************************************************",
      "*",
      "$0"
    ],
    "description": "The UniBasic SUBROUTINE command determines the beginning of an external subroutine"
  },
  "PROGRAM Skeleton": {
    "prefix": "PROG",
    "body": [
      "***************************************************************************",
      "* Program: $1",
      "* Author : Ian McGowan",
      "* Created: ${2:$CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE}
      "* Updated: $2",
      "* Comment: $3",
      "***************************************************************************",
      "*",
      "$0"
    ],
    "description": "The UniBasic PROGRAM command determines the beginning of a program"
  },
}

```

**Comment by dthiot** [comment]
Ian, I think that under your PROGRAM snippet, the “Created” line is missing “, at the end.

**Comment by brentlblair** [comment]
This is very cool.  I think it's more for adding code blocks, I'm looking
for something different.

I'm looking for custom autocomplete and documentation tied to the MV Basic
linter.
If I start to type 'OPEN' the linter shows OPEN, displays an example, and
shows documentation for the open verb.
In my example, I want to add a commonly used custom function
`DateTimeFormat` to a program that I am writing.
If I accept the autocomplete, it should add the full text to my program,
this way I have a working example, that I might just need to update the
variables in:
DateTimeFormat(inDate,inTime,'format')

If I hover over `DateTimeFormat`, it should show the help text:
Format internal data and or time in custom external format
You must have INCLUDE BP CustomLibrary in any program that references this
function
inDate=date in internal format - can be null if you do not need to convert
date
inTime=time in internal format - can be null if you do not need to convert
time
format=string using any combination of the follow characters, undefined
characters will be used as literals

Since we drive VSCode from Accuterm and setup the environments based on the
MBBasic json, we can drive this to all developers from our server.

The snippets functionality would probably work for individual developers
that just want to autocomplete chunks of code.

*Brent Blair* <http://www.linkedin.com/in/BrentLBlair>

Vice President of IT
Encompass
Phone 954.474.0300
Fort Lauderdale, FL
<https://www.google.com/maps/place/Encompass+Parts+Distribution/@26.145357,-80.2482168,12.46z/data=!4m5!3m4!1s0x0:0xb2bfe23d3412449!8m2!3d26.0920996!4d-80.2409538>

bblair@encompass.com
encompass.com

**Comment by ianmcgowan** [comment]
To be technically correct (the best kind!) "Linting" is different from "Intellisense", both are managed in https://github.com/mvextensions/mvbasic/blob/master/server/src/server.ts, in loadIntelliSense and validateTextDocument functions.

There is an option for a custom word list in server.ts/loadIntelliSense, but it's far from the "autocomplete" option you're looking for - if you specify a filename with a bunch of words in it, optionally wrapped in double quotes, it will color code those words.

It's a good suggestion to have a "custom intellisense list" parameter that did something similar, where you provide your own syntax file (perhaps from a central file share as you suggested) and it gets merged with the system provided one.  But absent that, you should be able to modify the appropriate Language.json file in the Syntaxes folder and add your own syntax definitions.  Sadly that will be lost every time the extension updates though.

The user snippet option does show some help when completing (and snippets autocomplete just like the built in intellisense), but it sounds like that's not centrally managed enough for your situation, plus it looks kinda sucky if you have a lot of description:

![image](https://user-images.githubusercontent.com/408975/85638422-b9377800-b63a-11ea-993d-f274581f101d.png)

**Comment by itsxallwater** [comment]
@brentlblair here's how I would approach this:

* Take a look at the [Language definition file for jBASE](https://github.com/mvextensions/mvbasic/blob/master/Syntaxes/jBASELanguage.json)
  * To extend the language definition we'll need to allow the extension to ingest JSON records that resemble the contents of this file--specifically, this array:
``` json
{
  "key": "$Include",
  "icon": 14,
  "index": 1,
  "documentation": "The $INCLUDE or $INSERT directive inserts the program/code snippet specified into the current source code.\r\nIf the optional filename is specified the code is read from that file.",
  "detail": "$INCLUDE programname\r\n$INCLUDE filename programname\r\n$INSERT programname\r\n$INSERT filename programname"
}
```
* The root `package.json` file has a section called [configuration](https://github.com/mvextensions/mvbasic/blob/a452ca52a0458cc76fe09e3d2f52a8cf4d8d83dd/package.json#L109) that will need to be extended to create the entry point for this custom JSON. You can look at the existing `customWordPath` setting which asks the user to specify a file to load from disk with the definition.
* The language server code at [server.ts](https://github.com/mvextensions/mvbasic/blob/a452ca52a0458cc76fe09e3d2f52a8cf4d8d83dd/server/src/server.ts#L146) has a `loadIntellisense` function that takes care to interpret the `languageType` setting for the extension and load the appropriate file in, so this is the section we'd want to tack on any custom definition as well.

**Comment by brentlblair** [comment]
I have the functions autocomplete working now.
![Code_0ZkcLh1XjP](https://user-images.githubusercontent.com/23214321/91217113-01c7ec00-e6e5-11ea-89a9-2e1bf1b827be.png)
I also changed it to use key along with insertText which will allow me to type 'DateTimeFormat' and autocomplete
"DateTimeFormat(internalDate,internalTime,'formatString')"
This also tells Intellisense that the hover word is 'DateTimeFormat' and will continue to show documentation even after you change the function vars in the code.
Do I need to do a pull request to get my changes ready for production?

**Comment by itsxallwater** [comment]
A PR would be great, against the `develop` branch specifically as we aggregate changes there prior to releasing.

If you could include relevant doc updates for this new feature that'd be excellent as well. Nice work!!!

**Comment by itsxallwater** [comment]
2.0.9 released! Closing issue.
