### ISSUE TITLE
[FEATURE] Add UniVerse Language Syntax

### ISSUE THREAD

**Issue by itsxallwater** [mvextensions/mvbasic#12]
**Is your feature request related to a problem? Please describe.**
Currently, the `client\Syntaxes\MvLanguage.json` file contains MVON# Basic syntax. We are looking to include UniVerse syntax out of the box to have available as an option within the extension.

**Describe the solution you'd like**
An acceptable pull request for this issue would include a UniVerse version of the MvLanguage.json file that can be included in the base package. This pull request need not concern itself with any of the plumbing for the extension to be able to dynamically load that syntax into place, we're simply looking for the syntax definition here.

**Comment by JeffTeter** [comment]
I would like to give this a go... I assume I can use the pattern already created by the jBase file. Also, is there a need to create separate files for various versions of the language?

**Comment by dthiot** [comment]
Jeff,

What kind of versions of the language are you thinking of?

Dick

**Comment by JeffTeter** [comment]
Versioning referencing new features added, for instance, between 11.3.1 & 12.1. Not major issues, but a few new items.

**Comment by itsxallwater** [comment]
Hey @JeffTeter! Great question and honestly, something we'd not yet addressed. I think for now the safest assumption would be to target the latest release, that's what has happened thus far with respect to the MVON# Basic language definition as well as the jBASE. Supporting previous versions of a respective language's definition/documentation would be very nice and slick as a follow up improvement to the language definition module but I don't think we're quite there yet to be honest.

By all means give it a go on creating the definition though! Note you'll also want to look at providing an updated version of `client\Syntaxes\MVON.tmLanguage.json` which is something I missed in the original description of these requests. That file informs on the syntax highlighting that should occur.

**Comment by JeffTeter** [comment]
Thanks for the note. I'm actually making good progress with 592 elements defined. 

At this point, I'm thinking that rather than providing separate files, I may just note in the description something like "(v12.1 & above)" for new features. 
A couple of other quick questions: 
1. Can you point me at a source for the icons?
2. Is there any magic in the index, other than being unique?

Thanks!

**Comment by itsxallwater** [comment]
Nicely done! I like your approach, I think that's perfectly reasonable.

1. The icons map to this [CompletionItemKind Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.languageserver.protocol.completionitemkind?view=visualstudiosdk-2019) from Microsoft. I think this document reads better than the one they've got in the VS Code Extension authoring docs. Unfortunately I haven't found any great visuals.
2. No not that I'm aware of and to that end, the jBASE ones were re-ordered to flow alphabetically in the doc for easier maintenance.

**Comment by JeffTeter** [comment]
Thanks for the info. I'm just about done with the UniVerse language file. I notice that your keywords are sentence cased. Is that the preference? I guess being an old developer, I'm used to SHOUTING instructions! :-) Also, I got functions and constants identified easily enough. Since UniVerse is not object oriented, seems like most other keywords are just that... Rather than constructors, etc...

**Comment by itsxallwater** [comment]
I wouldn't call it a preference by any means. I'm okay with saying your call on it. Thanks for putting in some work!!

**Comment by JeffTeter** [comment]
itxallwater,

I have the "UniVerseLanguage.json"

 file wrapped up. Sorry for the delay. I'm a bit unclear on the use and syntax for the "UniVerse.tmLanguage.json" file and could use some help on it... Suggestions?

**Comment by itsxallwater** [comment]
The best thing to do, to visualize things, would be to create (if you haven't already) a sample UniVerse BASIC program with all of the syntax you would like to test. When you load that file up in VS Code and use the MVON# language definition, it will do the highlighting based on the mvon.tmLanguage.json file. Then, you can modify the existing mvon.tmLanguage.json file to tweak the highlighting as needed for UniVerse.

In my estimation that's the simplest way to play with it. On the whole, the tmLanguage files are a series of Regular Expressions that handle the string parsing and color coding, so it's easiest to start with an existing. What you'll find, more than likely, is subtle differences in how you might want to color things for UniVerse versus MVON. That was essentially what Mike Street went through when creating the jBASE version. Hope this is helpful!

**Comment by JeffTeter** [comment]
Thanks for the response. I'm playing with that now and hope to learn the
finer points. I think I have the language file set up. Do these
configuration files get "baked into" the distribution package?

Have a great night!

Jeff

**Comment by itsxallwater** [comment]
They will indeed get baked in, great question :)

**Comment by JeffTeter** [comment]
Mike, I have the language file done, I believe, along with the "UniVerse.tmLanguage.json" file. What's the next step? Thanks!

**Comment by itsxallwater** [comment]
Hey Jeff, that's exciting and awesome news! Check out https://github.com/mvextensions/mvbasic/issues/23#issuecomment-518792959 which has some info on creating a fork of the project and submitting a pull request. Since you're an org member you may be able to create a branch here and submit a pull request using that, but if you're more comfortable it's acceptable to fork it and go that route.

**Comment by itsxallwater** [comment]
I should add that if you want to go the branch route, you can follow along with what I've done for #8 and pull request #28 to get a sense for how that works.

**Comment by itsxallwater** [comment]
Closed by #32

**Comment by nlehman06** [comment]
So if I wanted to use this language syntax, along with the UniVerse snippets, what steps do I need to take?  Currently, when I install this extension and change the language to mvbasic it is just using the MVON language and snippets.  My workaround is to update the package.json for the extension and point to the UniVerse destinations for the tmlangauge and snippets.  Is there a better way?

**Comment by itsxallwater** [comment]
Hey @nlehman06 that'll get you most of the way there but honestly it may be easier to rename the files, as there are three in total and while two are controlled in the `package.json` file, the third is controlled in code for the language server.

`UniVerseLanguage.json` to `MvLanguage.json`
`UniVerse.tmLanguage.json` to `mvon.tmLanguage.json`
`snippets-universe.json` to `snippets.json`

The idea is to execute on #14 to allow for this to be configuration driven but there's some nuances to work through there still.
