### ISSUE TITLE
[BUG] Auto-Complete list of subroutines keeps growing, and across tabs

### ISSUE THREAD

**Issue by kpowick** [mvextensions/mvbasic#127]
Each time the auto-complete list is displayed, the number of entries for every subroutine name in the program grows by one entry per subroutine.

For example, if the program has 2 subroutines **_SUB.01_** and **_SUB.02_**, the first time the auto-complete list is displayed you see:
SUB.01
SUB.02

The second time it shows:
SUB.01
SUB.01
SUB.02
SUB.02

The third time it shows:
SUB.01
SUB.01
SUB.01
SUB.02
SUB.02
SUB.02

And so on, and so on, for each time it is displayed.

<img width="287" alt="Screen Shot 2020-09-16 at 15 41 49" src="https://user-images.githubusercontent.com/1646753/93384698-2ec67500-f833-11ea-9168-627df2fd20d0.png">

The second problem is that the growing list is carried across separate documents (tabs) within the same VS Code window. i.e.  All document tabs within a window, with the language mode set to "MultiValue Basic", will show the growing list of subroutines from other tabs. 

So, you're editing one program, but seeing the subroutines (repeated) from a different program that's on a separate tab.  Note that this does not happen across separate VS Code Windows, just the tabs within one window.  

**O/S**
macOS 10.14.6 (Mojave)

**MV Extension**
2.0.11

**VS Code**
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Comment by itsxallwater** [comment]
Fixed in `develop` and will be included in release 2.1.3. Thanks @kpowick and @tcharts-boop! 🥳
