### ISSUE TITLE
Add user variables to the Intellisense array [FEATURE]

### ISSUE THREAD

**Issue by brentlblair** [mvextensions/mvbasic#128]
Add user variables as they are typed to the Intellisense array so they can be used in autocomplete.
This should also work with renamed and deleted user variables.

**Comment by brentlblair** [comment]
I now have the adding of user variables working on my local copy.  I have not figured out how to remove existing variables before they are renamed or deleted.

**Comment by brentlblair** [comment]
The solution is to clear all of the Intellisense items that are CompletionItemKind.Variable and add them back.  I don't know if this is the most efficient way of doing it, but it seems to work.

**Comment by brentlblair** [comment]
I have completed the changes and added MVBasic.userVariablesEnabled as a setting that defaults to false that can be used to activate this feature.  Pull request #129

**Comment by itsxallwater** [comment]
PR accepted and published as v2.1.0! Closing this.
