### ISSUE TITLE
[FEATURE] Display only certain sub-directories in the Explorer

### ISSUE THREAD

**Issue by ShafferButtars** [mvextensions/mvbasic#132]
I am working with a bloated account that has a few source code directories and configuration directories that I care about among thousands of files and folders that I don't care about.  All of them show in the Explorer view in VSCODE and it's extremely difficult to navigate to the few (or one) I care about.

I'd like to see a way to either 

1. Specify only certain directories to be displayed in the explorer area of VS Code. 
2. Or Define a root directory when calling VSCODE from the host command line (so, if I started it like VSCODE MVLIB MYPROG, it would bring MYPROG up in the editor, but the explorer view would be limited to the MVLIB directory).

Or something similar to one of those things.  I just need the ability to limit the scope of displayed explorer items down to a few specific directories and the items within them.

I've tried using VSCode's in-line search for the directories, but it doesn't work because there are several similarly named directories.  I've looked at the bitmask setting in the ACCUTERMCTRL, but the SelAttr setting only lets me filter by type of attribute and the files.exclude setting would require entering hundreds of directories and files for each workspace for that to work. I see other setting files in the ACCUTERMCTRL directory, but I don't see anything obviously helpful.

I recognize that a cleaner UniVerse account would make this a non-issue, but I don't have that choice, I'm working on a legacy system that is the way it is. 

If this is already possible and I'm missing it, I apologize but would appreciate pointing me in the right direction.

Thanks for all your efforts on this, I'm very excited about it.

**Comment by pschellenbach** [comment]
There is an update for the AccuTerm host programs that should help with this. One of the big differences with VSCode vs WED is that WED does not automatically populate the file system tree, but VSCode does. This host program update lets you list the files you want to show in the file browser so you can show only the files you want. Here's a link to the github issue: https://github.com/zumasys/accuterm-host-programs/issues/2 . This has not yet been included in an AccuTerm build yet but will be in the next release.



Peter Schellenbach | Director of Product Development
Zumasys Inc.
818-658-1592 | 866-582-8447
peters@zumasys.com | www.zumasys.com
1050 Calle Amanecer, Suite A | San Clemente, CA 92673

**Comment by ShafferButtars** [comment]
Thank you for the information and clarification.
