### ISSUE TITLE
[BUG] Add Line Comment on SSH session inserts \*

### ISSUE THREAD

**Issue by stuboydl** [mvextensions/mvbasic#158]
When editing over an SSH Remote session, using the Add Line Comment command inserts **\\***

**To Reproduce**
1. Install MS Remote - SSH extension
2. Install MV Basic extension
3. Connect to linux host through ssh and start editing a file with mvbasic language mode.
4. Use Ctrl-/ or Ctrl+K,Ctrl+C or F1 - Add Line Comment
5. Line is prefixed with **\\*** (backslash asterisk)

**Expected behavior**
Line should be prefixed with **\*** (asterisk only)

**Screenshots**
![image](https://user-images.githubusercontent.com/19900402/129675107-08d29176-a77b-41b2-aecc-040e4601d844.png)

**Versions of applicable software**
  * Windows 10/11
  * RHEL 7
  * Remote SSH

**Comment by kpowick** [comment]
You may be able to change this in the file `language-configuration.json`.

<img width="487" alt="Screenshot 2021-08-17 at 1 35 46 PM" src="https://user-images.githubusercontent.com/1646753/129774609-757bcd44-e7bd-4322-92a4-b3b3956f3478.png">

You should find that file in the `extensions` folder of your VS Code installation, under the subfolder `mvextensions.mvbasic-2.1.x/client`

**Comment by stuboydl** [comment]
Thanks - that works for local changes but not for an SSH session.

**Comment by stuboydl** [comment]
Changed on the remote ~/.vscode-server/extension...

**Comment by itsxallwater** [comment]
Glad you got this sorted! Thanks for the assist @kpowick.
