### ISSUE TITLE
[FEATURE] Add OpenQM Code Snippets

### ISSUE THREAD

**Issue by itsxallwater** [mvextensions/mvbasic#17]
**Is your feature request related to a problem? Please describe.**
Currently, the `client\Syntaxes\snippets.json` file contains generic Code Snippets. We are looking to include OpenQM-specific snippets out of the box to have available as an option within the extension.

**Describe the solution you'd like**
An acceptable pull request for this issue would include an OpenQM version of the `snippets.json` file that can be included in the base package. This pull request need not concern itself with any of the plumbing for the extension to be able to dynamically load those snippets into place, we're simply looking for the definition here.

**Comment by andrewcole50** [comment]
Pull request submitted. I'm sure various improvements/enhancements will be needed but the setup work is done.

One thing to note is how to handle optional arguments for functions and statements.
