### ISSUE TITLE
[FEATURE] Add UniVerse Code Snippets

### ISSUE THREAD

**Issue by itsxallwater** [mvextensions/mvbasic#19]
**Is your feature request related to a problem? Please describe.**
Currently, the `client\Syntaxes\snippets.json` file contains generic Code Snippets. We are looking to include UniVerse-specific snippets out of the box to have available as an option within the extension.

**Describe the solution you'd like**
An acceptable pull request for this issue would include a UniVerse version of the `snippets.json` file that can be included in the base package. This pull request need not concern itself with any of the plumbing for the extension to be able to dynamically load those snippets into place, we're simply looking for the definition here.

**Comment by JeffTeter** [comment]
Just out of curiosity, does VSCode support language snippets and separate snippets for the user/company. For instance, in the sample snippets file, I have seen a program skeleton but my organization has a different format for program skeletons. So, should I anticipate modifying the general UniVerse snippets or is there an option for having a separate user file?

**Comment by itsxallwater** [comment]
Hey @JeffTeter, in short, yes there is some capacity and our intention is for a user supplied file to overload any defaults. So you wouldn't have to delve into modifying the extension's internal files and instead, could configure a file for the extension to consume to perform the overload.
