### ISSUE TITLE
[FEATURE] Add sample Workspace Configurations & update Docs

### ISSUE THREAD

**Issue by itsxallwater** [mvextensions/mvbasic#21]
**Is your feature request related to a problem? Please describe.**
New users looking to setup a workspace to connect with a supported Pick server may experience a little frustration getting started. The documentation does cover configurations, but it needs to be updated to include the latest configuration options.

**Describe the solution you'd like**
Update the docs and also introduce a new `samples` folder to the project to include sample workspaces born straight from the docs.

**Comment by itsxallwater** [comment]
Note @dthiot is in progress on this so assigning to him!

**Comment by dthiot** [comment]
I have updated the documentation with standardized sample configurations.  I still need to add mvBase as a configuration.

**Comment by andrewcole50** [comment]
How accurate is the current documentation? I don't believe the Jbase section is as it uses GatewayFS while the changelog says it only uses RestFS (which doesn't work for me). The settings used for Jbase in the docs aren't in the extension anymore either.

**Comment by dthiot** [comment]
Andrew,

We are in the process of updating the documentation however, attached is the latest copy.  Please let me know if you find any issues with it.  It shows jBASE with a RestFS configuration example.

Thanks,
Dick

**Comment by andrewcole50** [comment]
The attachment didn't seem to work. I sent you a direct email about it.

**Comment by dthiot** [comment]
Just FYI to the team.  I have emailed the most current PDF to Andrew.

**Comment by itsxallwater** [comment]
Thanks for jumping on that @dthiot and big thanks for @andrewcole50 for the inquiry. I've linked the commits to this repo that had the corresponding doc updates but said doc updates should also be in the clone of the repo for the master branch. Just for the record :)
