### ISSUE TITLE
[FEATURE] Update Naming Conventions

### ISSUE THREAD

**Issue by itsxallwater** [mvextensions/mvbasic#22]
**Is your feature request related to a problem? Please describe.**
The project still references MVON and ONgroup. Need to update to change MVON references to MV Basic and ONgroup references to MV Extensions.

**Describe the solution you'd like**
Make the name changes, specifically focusing on extension configuration names and publisher info but elsewhere as acceptable/necessary.

An example where **not** necessary, the `client\Syntaxes\MvLanguage.json` file referencing "MVON# Basic" as a Language type.

An example where necessary, the `client\src\extension.ts` file referencing "mvon" as the configuration namespacece

**Comment by itsxallwater** [comment]
Note that @CharlesBarouch is in progress on this so assigning to him!

**Comment by dthiot** [comment]
I took much of the reference to ONgroup and MVON# out of the documentation.  However, I wasn't exactly sure how to replace it and chose MVextensions.

**Comment by itsxallwater** [comment]
@CharlesBarouch thanks for the commit, I've not yet had a chance to look but will try to do so and get you notes. @GrantHart if you wanted to peek here's just a tag to give you a heads up that Chuck got some name changes committed for the team to review w/ commit https://github.com/mvextensions/mvbasic/commit/15998ccabc29f83e4bca24d5dfd25c0df140b1e2.

**Comment by itsxallwater** [comment]
Name changes have been pushed to master. Thanks @CharlesBarouch!
