### ISSUE TITLE
[FEATURE] Create VS Code Marketplace page

### ISSUE THREAD

**Issue by MVDBMS-Solutions** [mvextensions/mvbasic#36]
When this updated project is ready for public beta, a new extension page should be published and linked to this repo.

tags: MultiValue, MVDBMS, BASIC, MVBASIC, Pick
categories: Programming Languages, Snippets, Linters

To be discussed : Who manages = publishes the extension? ONgroup? Zumasys? Other?

**Comment by itsxallwater** [comment]
Just a touch to say yes, definitely that will happen. Also as it pertains to the publishing, a mixture of all of the above. We've got the organization registered with Microsoft with a number of people added and set to be able to publish. That said, if I had to guess, I'll be the guy driving for a bit.

We're targeting a publish by the beginning of next week. @dthiot is just cleaning up a final few pieces of the docs.

**Comment by itsxallwater** [comment]
We're officially published at https://marketplace.visualstudio.com/items?itemName=mvextensions.mvbasic. As you may notice, the extension's page is a replication of the readme. I'm going to re-org some of the order of it, as it doesn't make sense to have the dev notes up at the top.

**Comment by MVDBMS-Solutions** [comment]
This ticket was purely about creating the page. That's been done. This ticket is closed. Thanks guys!
