### ISSUE TITLE
[BUG] Documented Goto/Peek is not working

### ISSUE THREAD

**Issue by MVDBMS-Solutions** [mvextensions/mvbasic#39]
Goto/Peek does not seem to be available. Tried with both numeric and alpha labels.

**To Reproduce**
1. Create a new file.
1. Paste in BASIC code that includes a GOSUB and a label.
1. Right click on the label in the GOSUB

**Expected behavior**
Context menu option to jump to label

![image](https://user-images.githubusercontent.com/41167191/65529734-8b56b480-deab-11e9-9f11-9e7d8a606a0b.png)
![image](https://user-images.githubusercontent.com/41167191/65529450-fbb10600-deaa-11e9-9cc6-408e55c4b817.png)

**Versions of applicable software**
  * Windows 8.1
  * Not connected to DBMS
  * MVBASIC Extension v2.0.0
  * VSCode 1.38.1

**Code sample**
```
GOSUB FOO
STOP
FOO: RETURN
```

**Comment by itsxallwater** [comment]
For me this appears to be tied to the program not being saved to disk. As soon as I save it, the context menu items show up. Up until that point, they are missing.

I believe this is addressable though and that we can initialize the language server for both items in memory and on disk. That would also solve for intellisense not loading until you start typing in the document.

**Comment by MVDBMS-Solutions** [comment]
This was resolved after updating to v2.0.1 and reloading. Per #41, the reload is what triggered linting functionality.
