### ISSUE TITLE
[BUG] Save to local file system forces .bas file extension

### ISSUE THREAD

**Issue by MVDBMS-Solutions** [mvextensions/mvbasic#40]
Attempt to save file to local file system. It seems to include the option to use any filename. With or without periods in the filename itself, ".bas" is always appended to the end.

The filename must not be altered from user specification.
![image](https://user-images.githubusercontent.com/41167191/65530147-41ba9980-deac-11e9-8db0-7845b31237d8.png)

Files without an extension should be allowed:
![image](https://user-images.githubusercontent.com/41167191/65531441-b7c00000-deae-11e9-86ce-cc7b718d68af.png)

This may only be true for an initial Save. With Save As, files can be saved without the extension, but Windows tries to default in a new .txt extension:
![image](https://user-images.githubusercontent.com/41167191/65531641-34eb7500-deaf-11e9-8531-9e7bbe0e5265.png)

**Versions of applicable software**
  * Windows 8.1
  * Not connected to DBMS
  * MVBASIC Extension v2.0.0
  * VSCode 1.38.1

**Comment by itsxallwater** [comment]
Replicated. This should be addressable as well, and may be linked in some capacity to what happens with default/standardized extensions (in discussion at #38).

It's not ideal but I've observed that at the moment, if you wrap the file name in quotes it will not append `.bas` to the end.

**Comment by ianmcgowan** [comment]
This changed in VSCode at some point.  If you open a file with no extension it will happily save without.  But if you start a new file you need to select "No Extension" as the filetype (and then you'll need to select the language again ^K M MV).

![image](https://user-images.githubusercontent.com/408975/65536252-e8f0fe00-deb7-11e9-8db6-43c7e4e98fc7.png)

**Comment by ry4nolson** [comment]
i think this is just the way windows works. If there is a type selected, it appends that extension. Notepad does the same thing. 
https://i.imgur.com/cqKTODR.gifv

**Comment by MVDBMS-Solutions** [comment]
@ianmcgowan I just searched for VSCode and Electron issues, found the answer you cited amongst many notes posted over the years on this topic, went back into VSCode to get a screenshot, and .... you already have it. HAHA Good man!
Thanks all. Problem solved. Not an issue with this extension.
