### ISSUE TITLE
[BUG] /* comments are not being recognised as comments

### ISSUE THREAD

**Issue by garoke** [mvextensions/mvbasic#49]
Comment prefix /* is not recognised by syntax linting and highlighting 

**To Reproduce**
Comment any code line by prefixing with /* or highlight a block of text and press Ctrl+/ 

**Expected behavior**
Code prefixed with /* should be colored in the same way that lines commented with the * prefix are. 
Code prefixed with /* should be excluded from linting rules

**Comment by dthiot** [comment]
garoke,

Thanks for your input.  What flavor up MultiValue database supports /* */ for block comments?

Thanks,
Dick Thiot

**Comment by garoke** [comment]
HI Dick,

None that I'm aware of. The commenting I refer to is the /* line commenting prefix. Highlighting a block of text and using the comment command prefixes all lines with /* it doesn't wrap the block in /* */ 

E.g.

/* IF SUCCESS THEN
/*    CALL DO.STUFF()
/* END

The prefixing with that character doesn't appear to be a problem when compiling etc. rather it's the fact that linting and hightlighting in the editor still treat as active code, even though the code is effectively commented out.

Hope that clarifies.

Best,
Gary.

**Comment by dthiot** [comment]
Gary,

I understand that the linter is the problem and I greatly expanded on the concept of your comment because I have wished for many years to have block comments supported by the MV compilers.  I can see how /* could be a valid comment, I just haven’t run across that before.  Which vendors support that?

Thanks,
Dick

**Comment by itsxallwater** [comment]
@dthiot As it turns out we may actually support this within jBASE (I've not verified yet); however, what Gary is saying is that when using the extension, if he uses the VS Code shortcut for adding a block comment the extension is using /* rather than * or !. That would be something under our control.

Bonus points on this will be if it turns out jBASE does support it, we can amend the jBASE language file to signal that block comments can be done with /*.

**Comment by itsxallwater** [comment]
Sorry I also understand that might not be immediately clear given the original post, I've got an inside track on this as Gary's with one of our clients and we were chatting on this on the phone earlier :)

**Comment by dthiot** [comment]
Mike,

I understand now after Gary updated me what he meant.  Thanks for your comments too.

Dick

**Comment by andrewcole50** [comment]
Related to this: comment syntax highlighting isn't working in the released version as it did for my last pull request regarding comments. I checked and scripts are all the same. I've been planning on looking into this and haven't had time lately. Also, this /* wasn't an issue until the official release as I use the keyboard shortcut for comments a lot and it was working fine prior to release.

**Comment by janvsc** [comment]
I would prefer if the Block Comment chars can be specified and not default to \*
Perhaps in json settings for mvbasic?
In UniVerse I personally prefer a *

**Comment by kpowick** [comment]
This setting can be changed by modifying the configuration file `language-configuration.json`, which is found in the folder `.vscode/extensions/mvextensions.mvbasic-2.0.6/client`

Open the file with a text editor and change the values for `lineComment` and `blockComment`  as desired.  Restart VS Code to enable your changes.

```
"comments": {
        "lineComment": "\\*",
        "blockComment": [ "/*",  "*/" ]
    },
```

**Comment by janvsc** [comment]
> This setting can be changed by modifying the configuration file `language-configuration.json`, which is found in the folder `.vscode/extensions/mvextensions.mvbasic-2.0.6/client`
> 
> Open the file with a text editor and change the values for `lineComment` and `blockComment` as desired. Restart VS Code to enable your changes.
> 
> ```
> "comments": {
>         "lineComment": "\\*",
>         "blockComment": [ "/*",  "*/" ]
>     },
> ```

Works perfect even my a space. Used "***** "

**Comment by janvsc** [comment]
Do we overwrite the language-configuration.json file when new versions are instlled?

> This setting can be changed by modifying the configuration file `language-configuration.json`, which is found in the folder `.vscode/extensions/mvextensions.mvbasic-2.0.6/client`
> 
> Open the file with a text editor and change the values for `lineComment` and `blockComment` as desired. Restart VS Code to enable your changes.
> 
> ```
> "comments": {
>         "lineComment": "\\*",
>         "blockComment": [ "/*",  "*/" ]
>     },
> ```

**Comment by itsxallwater** [comment]
That is correct
