### ISSUE TITLE
[BUG] Compile Basic Program command for Unidata

### ISSUE THREAD

**Issue by KieranFleckney** [mvextensions/mvbasic#50]
I work on a Unidata system and found this extension which is great however cannot compile it.

When trying to compile a program using the "Compile Basic Program" I get an error.
![image](https://user-images.githubusercontent.com/57374898/68215183-b538e600-ffd6-11e9-82a7-0aa13bff66c0.png)

However if I use the Debug version it works.
![image](https://user-images.githubusercontent.com/57374898/68215233-cbdf3d00-ffd6-11e9-8646-9abb5de094c5.png)

I've tested with a few differnent programs. I can't even get this to compile.
![image](https://user-images.githubusercontent.com/57374898/68215381-0b0d8e00-ffd7-11e9-9105-ca54f7192244.png)

I have debugged the client side and when it return from the REST call it doesn't pick it up as an error, however doesn't acutely compile the program on the Unidata side. Maybe I'm wrong not very familiar with VSCode extensions. An without see what the gateway doesn't couldn't find a reason for this happening.

Host OS: Windows 10
Remote OS: Window server 2012 R2

**Comment by ianmcgowan** [comment]
Would you mind sharing your config for unidata? I’ve been struggling to get
it to work (despite help from Dick).  A working example may help pinpoint
what I’m doing wrong.

**Comment by KieranFleckney** [comment]
Hope this helps
[udtconfig.txt](https://github.com/mvextensions/mvbasic/files/3832213/udtconfig.txt)
Forgot to add that I'm running Unidata 8.2.1

I will try again on another server with a fresh copy of Unidata running also, to see if I can replicate it myself too.

**Comment by dthiot** [comment]
Thank you Kieran.  I think that Ian was referring to your VSC Workspace config.

**Comment by ianmcgowan** [comment]
That’s the one, thanks Dick!

**Comment by KieranFleckney** [comment]
Oh okay, here you go.
[VSWorkspaceConfig.txt](https://github.com/mvextensions/mvbasic/files/3840292/VSWorkspaceConfig.txt)

**Comment by ianmcgowan** [comment]
Thanks for this - helped figure out my problems.  The main one being not using a workspace in VSCode, and also not noticing MS Word smart quotes when pasting example configs from the document.  Rookie moves!

I'm able to compile and catalog, but for my application it has to be in mode P, not mode U, and the catalog should be direct not global.  Can't figure out how to tell the gateway that though...

**Comment by ianmcgowan** [comment]
@KieranFleckney - try opening your program from Unidata in AE, and set "Unprintable characters shown" with "^".  I see that editing and saving is having a problem with line endings.  I'm on AIX so need a line ending of LF, and also a system used with Asian characters, so ^254 is not @AM on the server side.

**Comment by ianmcgowan** [comment]
For MvGateway, is there any tip to get it logging verbosely?  I'm sure it's something I'm doing wrong, but I haven't been able to get any logs out of it, ever.  I have the following in my workspace config, courtesy Kieran.

```
"MVBasic.RemoteDebug": true,
"MVBasic.gatewayDebug": true,
"MVBasic.trace.server": "verbose"
```

**Comment by KieranFleckney** [comment]
@ianmcgowan Yeah I add them in the config, however couldn't get it to log anything.

Yeah I saw that Line ending issue too but didn't know if that was an issue with my enconding type? 

In regards to the compiling using type P and Direct I couldn't find a way either, don't believe it possible even config it to do that. Was gonna open that in an another issue.

**Comment by ianmcgowan** [comment]
I setup a developer/personal edition of UD on a redhat instance with
standard delimiters, and can confirm I'm getting exactly the same behavior
as you.  So it's not just the language group ID causing the problem (though
that is a different problem with the MVGateway - it is hardcoded for AM =
CHAR(254)).  I think this is an issue with the gateway, but that's hard to
dive into.

For my use case, it's helpful to have a local copy of the code, so I use an
extension that when I open or save a file, it's synced down or up to the
Unix/Linux server.  For you, can you map a drive to \\remotehost\WC and
open your basic programs from that mapped drive?  That doesn't help with
the gateway and compiling, but it does provide most of the other benefits
of the extension.

**Comment by KieranFleckney** [comment]
That's good you can replicated the issue. Can you even look at the Gateway code with out decompiling exe?
I have tried the map drive solution before however the compiling feature was really something I liked and made it easier.

Also did you find a solution to the Line ending issue?
