### ISSUE TITLE
[BUG] False Positive Undefined Label Error

### ISSUE THREAD

**Issue by WouterSchuchner** [mvextensions/mvbasic#51]
**Describe the bug**
See the screenshot.  I'm getting errors that say that the "remove.quotes" subroutine is not defined, yet it is defined.  The upper right pane shown in the screenshot shows the "remove.quotes" label line, and also shows a similarly formatted "get.id,format" label line.  No such errors are spit out for the "get.id.format" subroutine.

I have correct-on-save enabled.  If I remove the indent preceding the "get.id.format" label, saving puts the indent back.  But whether I indent the "remove.quotes" label or not, saving does not change it.

Note that I have tried removing the space+asterisk from the end of these label lines, which has no effect.

**To Reproduce**
1. Enable auto-correct-on-save in VS code
2. Move the attachment HEAT.API.txt to a VS code project
3. Save it (file/save)

The errors show up in the terminal window.

**Expected behavior**
I would expect to NOT get these errors, and that the "remove.quotes" label line works in the exact same way as the "get.id.format" line.

**Screenshots**
![image](https://user-images.githubusercontent.com/58006748/69284164-8e240c00-0bb3-11ea-9889-717c8acdbc41.png)

**Versions of applicable software**
  * Host OS - Windows 10 Enterprice
  * Remote OS - D3 (D3Linux10_2)
  * Extension - MVBasic
  * IDE - VS code 1.40.1

[HEAT.API.txt](https://github.com/mvextensions/mvbasic/files/3871852/HEAT.API.txt)

**Comment by ianmcgowan** [comment]
It seems to be related to the subroutine name starting with "REM", which is
probably not a coincidence.  If you rename the sub to rmove.quotes all
errors go away and it shows up in the breadcrumbs at the top of the
screen.  There may be some over eager parsing for REM at the start of a
line being taken as a comment?

**Comment by dthiot** [comment]
Thank you for reporting this.  I suspect that Ian is correct in that there is an issue with the parser for a line that begins with REM being a comment. You are more than welcome to download the source code and have a look if interested.  If not, just keep the reports coming and we will fix them as best we can.

Dick Thiot

**Comment by ianmcgowan** [comment]
I'd like to start doing development in the extension, and have done the
steps 1-6 on the "development setup", but the next steps are not that
obvious.  It would be awesome to have a "new developer" guide/cheat sheet,
that lays out the various areas and describes the overall architecture.
Since I'm brand new to javascript/vscode extensions, I'm keeping notes and
screenshots as things begin to come together and will collect those into a
developer guide.

**Comment by ianmcgowan** [comment]
Submitted pull request to fix the regex handling for REM, both for formatting (mvon.tmLanguage.json) and validation (server.ts).  https://github.com/mvextensions/mvbasic/pull/55

**Comment by itsxallwater** [comment]
@WouterSchuchner let's get together next week and I'll have you test against latest updates that are not yet published. Or if you want to just email me your code I'll take a peek :)
