### ISSUE TITLE
[BUG] Cannot read property 'substr' of undefined -> Code: -32603 

### ISSUE THREAD

**Issue by mikes-zum** [mvextensions/mvbasic#57]
Highlighting BASIC source code in both the stable and Insiders version of VS Code generates errors

**To Reproduce**
Use "Ctrl-A" on largest item being edited, or copy the path of one of the items being edited.
As expected, all lines of the item being edited are highlighted, and the path of an item is returned, but an error is thrown

**Expected behavior**
No error should be thrown with these operations

**Screenshots**
I[Server(25296)] Started and initialize received
[Server(25296)] Language definition loaded for jBASE]
[Server(25296)] Document opened: file:///d%3A/jBASE5/SandBox/PGM/SYNTAX.TEST.b
[Server(25296)] Document opened: file:///f%3A/Archive/QM/uvsave.b
[Server(25296)] Document opened: file:///f%3A/Archive/QM/QMSAVE.b
[Server(25296)] Document opened: file:///d%3A/jBASE5/SandBox/PGM/bittest.jabba
[Error - 16:41:05] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'substr' of undefined
  Code: -32603 
[Error - 16:41:05] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'substr' of undefined
  Code: -32603 

**Versions of applicable software**
Windows 10 1909 Build 18363.535
VS Code version 1.41.0
VS Code Insiders 1.42.0-insider
MVBasic.LanguageType = "jBASE".
[bittest.zip](https://github.com/mvextensions/mvbasic/files/3979568/bittest.zip)

"extensions": [
					".bas",
					".b",
					".jabba",
					"."
				],

**Code samples and/or reproduceable test cases**
Try requesting the path of the attached (zipped) .jabba item

**Additional context**

**Comment by itsxallwater** [comment]
@mikes-zum I think I have this bug crushed but ping me next week and we can peek at it together.

![image](https://user-images.githubusercontent.com/13155413/80266338-284f1b00-8650-11ea-9239-2e00a98c0c8b.png)
