### ISSUE TITLE
[FEATURE] Setup Extension Bundling

### ISSUE THREAD

**Issue by itsxallwater** [mvextensions/mvbasic#76]
**Is your feature request related to a problem? Please describe.**
Microsoft recommends [bundling Extensions](https://code.visualstudio.com/api/working-with-extensions/bundling-extension) especially for larger projects. We currently get a warning when running `vsce package` and `vsce publish` that we should consider it. This should be taken up as a performance improvement for the distribution of the extension.

**Describe the solution you'd like**
Ideally, follow the guide linked above to setup Webpack for bundling this extension,

**Describe alternatives you've considered**
Less an alternative and more of a parallel effort, we can also [add unnecessary files](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#.vscodeignore) to a `.vscodeignore` file to help reduce the extension size.

**Additional context**
Here's the current CLI output from `vsce package`:

> This extension consists of 9342 files, out of which 4541 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You shndle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

**Comment by kpowick** [comment]
I think an effort should be made to reduce the size of the shipped/marketplace extension by omitting unnecessary folders from the bundling.

After doing a size analysis of extensions in my own `.vscode/extensions` folder, we can see that `mvextensions.mvbasic-2.0.5` is by far the largest at 140.3 MB.  That's 70% of all my extensions and almost 6 times larger than the next largest extension in the list.

<img width="392" alt="Screen Shot 2020-04-21 at 15 00 46" src="https://user-images.githubusercontent.com/1646753/79903673-7ca09380-83e1-11ea-97af-f5800b692691.png">

In the next screenshot, we can see that a significant contributor to the size are the `doc` and `node_modules` folders.  I think that the `doc` folder can be completely eliminated (59.5mb), and surely we can reduce the number of packages in `node_modules`, can't we?

<img width="387" alt="Screen Shot 2020-04-21 at 15 01 07" src="https://user-images.githubusercontent.com/1646753/79904173-46174880-83e2-11ea-8399-8f3745f27b3b.png">

**Comment by kpowick** [comment]
Just wanted to follow-up and say thank you for the extension size reduction in `v2.0.6`. 

We went from 140.3MB in `v2.0.5` to 9.9MB in `v2.0.6` --  93% smaller!

<img width="397" alt="Screen Shot 2020-05-06 at 11 31 07" src="https://user-images.githubusercontent.com/1646753/81198108-1c882080-8f8f-11ea-93c1-69c44ccc63dd.png">
