### ISSUE TITLE
[BUG] Unable to resolve workspace folder w/ AccuTerm RestFS

### ISSUE THREAD

**Issue by Nick2253** [mvextensions/mvbasic#77]
**Describe the bug**
When I connect to the AccuTerm RestFS server, I get an error "Unable to resolve workspace folder" when attempting to browse through my filesystem.

I am using AccuTerm 7 w/ the VSCode plugin as a bridge for MVBasic.  I am able to successfully launch VSCode using the VSCODE command in AccuTerm.

I'm pretty sure everything is talking, because if I launch VSCode using `VSCODE <File> <Item>`, the editor immediately opens to editing that item.  For example, `VSCODE BP MYPROGRAM` and now I'm editing MYPROGRAM in VS Code.

**To Reproduce**
1. Open VS Code using VSCODE in AccuTerm.
2. Observe the "<ACCOUNT>" folder in the workspace (<ACCOUNT> is replaced with the correct account from my Universe system).
3. Attempt to open the <ACCOUNT> folder.
4. See the exclamation point and the error:  Unable to resolve workspace folder.

**Expected behavior**
I expect to be able to browse through my account, similar to how I would via WED.

**Screenshots**
![mvbasic](https://user-images.githubusercontent.com/926554/78820396-90350e80-798c-11ea-8c1d-4da29359b5e6.png)

**Versions of applicable software**
Detail on the versions of any and all pieces of software that are part of your environment, such as:
  * Client - Windows 10 w/ Accuterm 7.3 and VSCode 1.43.2
  * Server - RHEL 7.7 w/ UniVerse 11.3.1

**Comment by itsxallwater** [comment]
Thank you @Nick2253 we're chasing this now

**Comment by itsxallwater** [comment]
Pete's got a path on this and we should have a fix incoming soon

**Comment by pschellenbach** [comment]
I have identified at least one way that this error can happen. When the number of files in VOC / MD are more than the max items setting in the auto-created workspace VSCode shows this error status. You can edit the workspace template in the ACCUTERMCTRL file and change the max items to a larger number. @Nick2253  - could you give this a try and let me know? I modified the extension to show any errors like this so you will more easily diagnose the problem.

**Comment by dthiot** [comment]
Can we just limit the number of items returned from the select?  Lots of implementations implement SAMPLE in some form or another.  Does that make any sense?

**Comment by Nick2253** [comment]
@pschellenbach That seems to be the issue.  When I changed it from the default of 250 to 2500, everything came right up.
