### ISSUE TITLE
[BUG] Formatting adds spaces to blank lines within indented code

### ISSUE THREAD

**Issue by kpowick** [mvextensions/mvbasic#82]
**Describe the bug**
It seems that as of v2.0.4, the formatting feature is now adding spaces, as defined by the setting _"MVBasic.indent"_, to blank lines within indented code.  e.g.  Loops, If/Then, etc.

I noticed this when saving an existing program and my Git diff displayed the newly inserted spaces.

**To Reproduce**
1. In VS Code, enable View/Render Whitespace

<img width="235" alt="Screen Shot 2020-04-15 at 10 56 16" src="https://user-images.githubusercontent.com/1646753/79352609-14950d80-7f08-11ea-955c-0f3b2fa5f40c.png">

2. Add a blank like to a section of indented code and save it.  The formatter will add spaces to this blank line. 

**Expected behavior**
Blank lines should remain blank, as they did in previous versions.  No extraneous spaces should be added to a blank line, no matter where it is found.

**Screenshots**
In the screenshot below, line 78 is blank with no extra spaces because it is not within an indented section.  However, blank line 88 has extra spaces added because it is within an indented section.

IMO, this is not correct and not consistent with the behaviour of previous versions of the extension.

<img width="139" alt="Screen Shot 2020-04-15 at 11 05 24" src="https://user-images.githubusercontent.com/1646753/79353432-0bf10700-7f09-11ea-9b67-588d5298ea76.png">

**Versions of applicable software**
Detail on the versions of any and all pieces of software that are part of your environment, such as:
  * Host OS - MacOS 10.14.6
  * Remote OS - N/A
  * Extension - MV Basic 2.0.4
  * IDE - VS Code 1.44.1

**Comment by itsxallwater** [comment]
Thanks @kpowick my guess is this related to some of the regex changes that were made so we'll start there, thanks for raising

**Comment by kpowick** [comment]
I've added a PR for this, though you may have already covered it with what you're planning for issue #86.

**Comment by itsxallwater** [comment]
Thanks @kpowick! Will peek and get things merged in here before we generate 2.0.5.

**Comment by itsxallwater** [comment]
Merged, thank you sir!

**Comment by kpowick** [comment]
2.0.5 corrects the issue, so I'm closing it. I hope that is ok.
