### ISSUE TITLE
[BUG] Unable to save files.

### ISSUE THREAD

**Issue by Nick2253** [mvextensions/mvbasic#85]
**Describe the bug**
When attempting to save a file, I receive an error from VSCode.  I'm using the AccuTerm VSCode bridge.

```
Failed to save 'NIC.TEMPEMAIL': Unable to write file 'RestFS:/BP/BP/NIC.TEMPEMAIL' (Error: nodeNC failed:

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
)
```

I'm not sure if it's related, but when I launch `VSCODE` in AccuTerm, I get the following error on my terminal.  However, I'm able to open files just fine, so it doesn't seem to be a communication error:

```
Program "FTFSI": Line 754, Bad file descriptor.
Unable to encrypt the data: Master key has not been set up. See uvregen utility
documentation.
```

I have a Master key set up, so I'm not sure if that error is misleading, or there's something else going on there.

**To Reproduce**
1. Open a file.
2. Edit a file.
3. Attempt to save a file.

**Expected behavior**
I expect the file to be saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/926554/79480934-a746b280-7fc3-11ea-900d-a6b75f085c1b.png)

**Versions of applicable software**
Detail on the versions of any and all pieces of software that are part of your environment, such as:
  * Client - Windows 10 w/ Accuterm 7.3 and VSCode 1.43.2
  * Server - RHEL 7.7 w/ UniVerse 11.3.1

**Comment by Nick2253** [comment]
Further diagnostic info:

When I launch VSCode, I am able to freely browse through and open files.  Once I attempt to save, it's like I get kicked out.  I am then unable to browse or open files.

```
Unable to open 'NIC.TEST': Unable to read file 'RestFS:/BP/BP/NIC.TEST' (Error: nodeNC failed:

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
).
```

**Comment by itsxallwater** [comment]
@Nick2253 would you happen to be the same Nick with an email thread going with @pschellenbach and I right now? If not, can you grab the latest AccuTerm Host Programs from:

https://zdownload.blob.core.windows.net/accuterm/Host-Programs/Windows/x86/8.0.7.0/pickbp.exe

After updating the host programs in your AccuTerm installation, use `MultiValue` -> `Host Programs` -> `Install` in your newly created ACCUTERM account then report back?

Much obliged!

**Comment by Nick2253** [comment]
I'm a different Nick.

I'm using AccuTerm 7.  Is it compatible with the Host Programs from AccuTerm 8?  Before I install the programs, I want to confirm so I don't break anything, since we have multiple developers relying on WED.

**Comment by itsxallwater** [comment]
Well then, pleasure to meet ya!

Yes, you are clear to use those host programs with 7. Looking forward to hearing how that goes for you. CC @pschellenbach

**Comment by Nick2253** [comment]
Sorry that it took me forever and a day to respond, but that worked!  Thank you for the help.
