### ISSUE TITLE
[BUG] Lots of errors in pop up in output screen

### ISSUE THREAD

**Issue by janvsc** [mvextensions/mvbasic#86]
As discussed with Richard Thiot:

I've been using your mvbasic extension from the beginning.
However a while ago I've been getting weird error messages 100+ every time I load large BP programs.
I am not connecting to any server AFAIK
Simply loading the program from a folder

Starts off like this:
![image](https://user-images.githubusercontent.com/6188515/79532151-9a0af000-80b7-11ea-86c1-1c2661f2881e.png)

and ends like this:

![image](https://user-images.githubusercontent.com/6188515/79532171-abec9300-80b7-11ea-8845-cc6a6915b0ca.png)

This specific program is only 10194 lines long :-)
It is also giving similar errors on smaller programs.
I am on version 2.0.4 which s/b the latest?
This is UniVerse in PICK flavor programming. NOT connecting to the DB at all.
The output window pop up by itself and it is most annoying as it cover half the page.

As a work around I dragged the output window down to minimum size

**Comment by itsxallwater** [comment]
Thanks for raising this! I have good news 😃 

2.0.5 is about ready to drop on Monday and includes a fix for that console output. Those particular messages have been stripped entirely.

Additionally, by default you won't see any console/output channel logging, but the setting MVBasic.server.trace includes options to enable various levels in the event the extension needs to be debugged.

Overall you should find the experience much improved. Plus, the option to enable/disable auto formatting has been fixed, and the REST file system API has received a few fixes.

I will leave this open pending release to give you a chance to confirm. Appreciate you taking the time to log the issue!

**Comment by itsxallwater** [comment]
@dthiot and anyone time that might be curious those console messages were introduced in 2.0.4 as part of the regex updates to the language server. That version shipped with improved for/next pair detection but the console output was left in by accident.

**Comment by janvsc** [comment]
Looking forward to the new drop.
I will report back after installation :-)

**Comment by janvsc** [comment]
Will Monday be Tuesday in Australia?

**Comment by itsxallwater** [comment]
May depend on also shipping corresponding AccuTerm connector updates. In theory we could publish 2.0.5 now.

@pschellenbach let's catch up on this tomorrow in the event we could look to drop updates a bit earlier

**Comment by ianmcgowan** [comment]
@itsxallwater, thanks for catching this, it was me leaving some debug output in the code by mistake.

**Comment by itsxallwater** [comment]
All credit to Pete for the patch while he was adding some helpful debug messages for the connector and wiring them up to the server trace setting 😃

Does look like we might have a related thing to chase in #82 though.

**Comment by itsxallwater** [comment]
FYI 2.0.5 is live in the marketplace. Will get things release tagged here in the AM & Pete should also have his host program updates posted in the AM (Pacific).

**Comment by janvsc** [comment]
Installed fine. Will test some more during the day.
Will raise a new request for some silly output errors

**Comment by itsxallwater** [comment]
I'm fine for you to follow up here with any additional and we can continue to fine tune, if you like. Thanks for checking in!

**Comment by janvsc** [comment]
Still getting 191 Problems reported and when I click on one of the problems to investigate.
The output starts filling up with 'split' of undefined Code: - 32603 messages

**Comment by janvsc** [comment]
The so called problems are not problems at all.
Example:
REMOVE.ERR.LEGS is not defined as a label in the program MV bAIC [819,11]
Invalid GOTO or GOSUB

This is referenced twice as problems.

This is simply not true
The are two GOSUB REMOVE.ERR.LEGS in the program AND
The label does exist

There are 191 problems reported.
When I click on the first problem the output start reporting problems too.
So no. not fixed for me

**Comment by itsxallwater** [comment]
Would you be willing to share your full program, or a simpler, abstracted version that still contains your problem?

**Comment by dthiot** [comment]
Jan.

What does your label line look like?  Maybe the linter isn’t recognizing your label because of the way you have it constructed.  Obviously, the way you have done it works but the linter may not take your formatting of the label statement into account.  This is a stab in the dark as you may have a perfectly simple label.

Dick

**Comment by janvsc** [comment]
I am willing to share the entire program but not in public. Who can I email?

@dthiot  - Nothing wrong with the label

**REMOVE.ERR.LEGS:**

All the labels in the entire program is in this format

**Comment by janvsc** [comment]
Sorry. Tried to email the program but blocked by our Admin.

**Comment by kpowick** [comment]
I've found and corrected the problem with labels being unrecognized if they begin with `REM`, as in Jan's label "`REMOVE.ERR.LEGS`:".

I will post the PR shortly.

**Comment by kpowick** [comment]
I believe this will also solve issue #51

**Comment by janvsc** [comment]
Also clicking on the error take you to the incorrect place in the program

**Comment by janvsc** [comment]
Okay. managed to get a copy of the program.
Who can I email this to?

**Comment by itsxallwater** [comment]
mikew AT zumasys DOT com if you'd like. I can test @kpowick's PR against it in the AM and we can publish the updates pretty quickly from there.

**Comment by kpowick** [comment]
Just checking a few more things. I will post PR tonight.

**Comment by janvsc** [comment]
Email sent to Mike. Have fun. Only 188 problems :-)

**Comment by janvsc** [comment]
Also. when closing one program and opening another the output screen is not cleared.
Still shows all the output error from previous programs

**Comment by janvsc** [comment]
The example I sent is one of the worst cases :-)
However I have several others that have the same problem

**Comment by kpowick** [comment]
@itsxallwater Is there any chance the sample program from @janvsc can be added to the `/tests` folder of the project?  If not, would someone please send me a copy?

**Comment by itsxallwater** [comment]
I can send your way if @janvsc is okay with it. I think we'll have to avoid adding it to the repo though since it is their IP. If he gives the green light, just ping me at that zumasys address [above](https://github.com/mvextensions/mvbasic/issues/86#issuecomment-617526439) @kpowick.

**Comment by janvsc** [comment]
You may send it to @kpowick. Please do not post public. I don't mind if it is shared with the devs only.
