### ISSUE TITLE
[FEATURE] Document the File System REST API

### ISSUE THREAD

**Issue by itsxallwater** [mvextensions/mvbasic#89]
**Is your feature request related to a problem? Please describe.**
Now that there are two connection options using the File System REST API (MVGateway and AccuTerm), it would be good to add the API specs to the project for anyone else looking to customize a connector.

**Describe the solution you'd like**
A PR for this should include Postman or Swagger/OpenAPI specs for the File System REST API.

**Describe alternatives you've considered**
A Markdown file would be acceptable as an alternative.

**Comment by itsxallwater** [comment]
Handing to Pete due to familiarity plus acknowledging his intention, though if someone else feels comfortable I'm sure he'd appreciate the help!

**Comment by pschellenbach** [comment]
Closed by commit 6b9b8ee7
