### ISSUE TITLE
[BUG] $IFDEF/$ELSE/$ENDIF not recognized

### ISSUE THREAD

**Issue by dthiot** [mvextensions/mvbasic#95]
The terms $IFDEF/$ELSE/$ENDIF are not recognized by the linter as valid terms.  The ELSE in $ELSE is recognized but that isn't a surprise.

**To Reproduce**
Create a document with type MultiValue Basic and enter the following code:
$IFDEF Netbasic
$ELSE
$ENDIF

**Expected behavior**
Recognize these terms as valid statements.

**Versions of applicable software**
These commands may be platform-specific but this form is supported by Universe and others.  OpenQM may have the most support of compiler-directives of any of the MV platforms.

**Code samples and/or reproduceable test cases**
See above.

**Comment by kpowick** [comment]
If you mean the syntax highlighting, it should be an easy fix. 

I'll add the escaped keywords to the syntax files like is done with \\$INCLUDE

**Comment by dthiot** [comment]
Yes, I did mean the syntax highlighted.  My mind was 50% elsewhere.  I know what I was saying regarding the linter wasn’t quite right but I wasn’t paying enough attention to do anything about it.

**Comment by kpowick** [comment]
And, of course, the fix is a little more involved than just adding the keywords.  I'm into it right now and hope to have a fix relatively soon.

**Comment by kpowick** [comment]
@dthiot  PR #94 should close this issue.  A lot of important updates were made to that branch, so I'm guessing it will be merged into master soon.  

What do you think about a merge into master @itsxallwater ?

**Comment by itsxallwater** [comment]
I'd like to get some peer review in on it plus there are a few older issues I think are handled by it too that were reported by some of my coworkers. I'm following up with them today to chase agreement/awareness.

**Comment by kpowick** [comment]
I've been going through older issues that are corrected by this PR and linking the PR to them.  On the open issues list, It makes it easier to see which ones still need attention.

**Comment by itsxallwater** [comment]
Yes indeed and thank you for that, I was doing the same on Friday and I ended up assigning them to myself too. By all means feel free to do the same. I also just created this v2.0.6 milestone which you can tag them with.
