### ISSUE TITLE
[BUG] Using periods in labels

### ISSUE THREAD

**Issue by nlehmanDLC** [mvextensions/mvbasic#96]
I'm using VS Code 1.44 on Windows Server 2016.  I'm using version 2.0.6 of MV Basic.

I often use periods to separate words in my labels.  For example:
```
* Some method
SOME.METHOD:
      FOO = BAR;
      RETURN
```
When I run the code format, it does not recognize these as labels.

What I end up doing is changing your regex found in client\out\extension.js to:
```javascript
let rLabel = new RegExp("(^[0-9]+\\s)|(^[0-9]+:\\s)|(^[\\w.]+:)");
```

I have to do this each time you put out a new version of your extension.  It's no big deal but this time was a little bit of a pain since it was minified.

Would it be ok to add periods in the label regex or maybe an option that would let the user over-ride with their own regex?

Thanks so much for this extension.  It has helped me so much!

**Comment by kpowick** [comment]
Never noticed that before.  Thanks for the feedback.  I'll look at getting that RegEx fix into the next update.

**Comment by kpowick** [comment]
Actually, I cannot reproduce the issue.  Dot-separated labels in my own code, and your example, are recognized in 2.0.6.

If you check the folder `.vscode/extensions`, do you only have one version of `mvextensions.mvbasic-N.N.N`, where `N.N.N` is the version number (e.g. `2.0.6`)?

Perhaps try reinstalling via the following procedure:

1. Remove the extension via the Extensions panel in the VS Code application.
2. Close all instances of VS Code.
3. Under the folder `.vscode/extensions`, delete all folders named `mvextensions.mvbasic-N.N.N`.
4. Open VS Code.
5. Reinstall the extension from the marketplace.

**Comment by nlehmanDLC** [comment]
I had both `2.0.5` and `2.0.6` in my extensions folder.  I followed your steps to remove.  When I re-installed I still have the same issue.

Here are the customized settings I use for this extension:
```json
"MVBasic.useCamelCase": false,
"MVBasic.margin": 6,
"MVBasic.languageType": "UniVerse",
```

Here is a screenshot before I do code formatting:
![image](https://user-images.githubusercontent.com/17048440/81187182-b2b54a00-8f81-11ea-8d39-3f2f8704deb0.png)

And here is what happens after I run the code formatting:
![image](https://user-images.githubusercontent.com/17048440/81187397-0162e400-8f82-11ea-8d85-d2161e890551.png)


Adding a dot into that regex for rlabel fixes the issue for me.  Are there any other tests I can do that will help debug?

**Comment by kpowick** [comment]
Ok.  I see the issue now.  It's not the code linter, it's the syntax highlighting you're missing.  And the dot isn't the issue, it's the leading spaces (your margin setting) that is causing the highlighter to "miss" your labels.  Actually, non dotted labels have the same problem if the margin is greater than zero.

I'll get this fixed-up and post the RegEx for the next update here. 

Thanks for the extra details.

**Comment by kpowick** [comment]
I believe I have a RegEx fix for the syntax highlighting problem of labels beginning with spaces.  

The updated RegEx for label recognition is:  `"^\\s*([\\w.]+:(?!=)|[0-9]+)"`

Several files are affected, which you can review in [this commit](https://github.com/mvextensions/mvbasic/commit/77b961a124be0bfb5402ab99f02162ad2892667d).

**Comment by kpowick** [comment]
@nlehmanDLC, If updating your live install by hand, please be sure to check all commits as of 2020-05-06 in the [branch](https://github.com/mvextensions/mvbasic/commits/96-periods-in-labels) that I opened for this issue.

**Comment by nlehmanDLC** [comment]
The RegEx looks fine to me.  For me the addition of the dot was the important thing.  I didn't really need the part with the leading spaces which might have been confusing based on the screen shots I posted.  The first screen shot represents the way I wanted the code to be formatted, the second shows what happens after running the code format.  Since it wasn't being matched as a label it was indenting the label as part of the regular code.

**Comment by itsxallwater** [comment]
@kpowick I pulled your branch and ran a quick build to put together a preview for 2.0.7 with this change included. Might help out for testing. Easier to accomplish now that the final build output is tiny.

1. Take care to set the `version` in the `package.json` files (`vsce` can do this for you but for these sorts of things I like to keep it manual).
2. `npm run compile`
3. `npm run webpack`
4. `vsce package`
5. Zip and upload the `.vsix` file.

[mvbasic-2.0.7.zip](https://github.com/mvextensions/mvbasic/files/4588480/mvbasic-2.0.7.zip)

**Comment by kpowick** [comment]
@nlehmanDLC Sure thing, but I had to come up with a RegEx that solved more than just the "dot" problem.  Dotted labels actually work fine in 2.0.6, **IF** there are no leading spaces (margin) before the label.  Your report uncovered that problem.

Thanks again. Tweaking the syntax highlighting is an ongoing process.
