### ISSUE TITLE
[BUG] Issue with linting in server.js with multiple levels of quoting

### ISSUE THREAD

**Issue by ianmcgowan** [mvextensions/mvbasic#98]
Splitting lines on ";" to allow checking for problems is working well, and common cases where a semi-colon is embedded in a string "" or between parens is handled. Issue is that if there are quotes between parens, such as this example: `LEASE.TYPE=OCONV(ID,"TLS.MASTER,LS.BILLING;X;38;38")`

The line ends up getting split, and the parser thinks there are two labels 38 on separate lines.  Short term fix is to consider strings and parens separately, but long term a better regex would be more efficient.  Negative lookaround would be the answer?

**Comment by kpowick** [comment]
@itsxallwater did a lot of work on the linter for `v2.0.6`, so he can answer better than me.

One approach I thought about was a two-step process.  First, replace all quoted strings in a line with empty quotes `""`, then apply linting.  It's simplistic, but fairly easy.  I'm not sure how it would affect efficiency though.

**Comment by kpowick** [comment]
Ian, does your [commit](https://github.com/mvextensions/mvbasic/commit/4faac9706561c9f6075f4427ad78991e261a28d0) resolve the issue?  I did some quick tests and it seems to work correctly now.  Thanks!

**Comment by ianmcgowan** [comment]
Yes, but it seems hokey.  Quotes are treated as a group, so \"foobar;123"\
would still have an issue with splitting.  But treating parens as a
separate class does seem to resolve what's a more common issue - the code I
work with does a lot of X=OCONV(ID,"TFILENAME;X;23;23") rather than
READV's, and the quotes inside the parens was a problem.  The "right"
answer involves smarter use of regex with forward lookaheads - we want to
identify semi-colons *except* when inside a matched set of delimiters.

On the performance side of things, the whole validateTextDocument function
is surprisingly fast - 200-300ms on my PC with a large program.  It's
called for every keystroke though, so I wonder if some kind of "debounce"
makes sense, where we just return if it's been less than a second since the
last call.  It's running outside the main vscode thread, so doesn't seem to
impact interactive performance...

**Comment by kpowick** [comment]
> Yes, but it seems hokey. Quotes are treated as a group, so \"foobar;123"\ would still have an issue with splitting

As I mentioned above, why not just replace quoted strings with empty quotes `''`?

The content of a string has no effect on the validity of the code.  I recently updated the RegEx for quoted strings.  It's faster and more efficient.  Plus, I see this replace method already in use with regard to comments.  Maybe something like the following pseudo code .
```
if (qString.test(line.trim()) == true) {
   let qs = qString.exec(line.trim());
   line = line.trim().replace(qs[0], "''");
}
```

**Comment by itsxallwater** [comment]
I like where you guys are headed but won't have much availability near-term to get hands on with you.

> On the performance side of things, the whole validateTextDocument function
is surprisingly fast - 200-300ms on my PC with a large program.  It's
called for every keystroke though, so I wonder if some kind of "debounce"
makes sense, where we just return if it's been less than a second since the
last call.  It's running outside the main vscode thread, so doesn't seem to
impact interactive performance...

You're touching on exactly why the language server design pattern calls for a separate process, per Microsoft :) I think there is a way to control the debounce, as you say. If I were going to put time at it, I'd start by checking out where the official language server sample is at--they continue to update it and it's been a bit since we sync'd up to it. https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample

**Comment by ianmcgowan** [comment]
That would work for quotes, and true from a linting perspective strings can
be ignored. Could paren's be treated the same way? That seems riskier, but
not sure anything we're checking for in validateTextDocument() would be
affected?

There's this example in the D3 documentation:
locate(acontinent,continents,1;position;'al')
then crt acontinent:' is already there' to be handled.  I may be one of a
very small minority that will ever care about this ;-)

**Comment by kpowick** [comment]
I think that for the current level of linting being done, replacing parens with empty ones `()`, would probably be ok in the short term.  However, I agree with Mike that we should eventually move to using a language server.

A language server offers much more in terms of both performance and deeper/better linting capabilities.  Also, if I understand correctly, a language server for MV can be plugged into other tools that support the Language Server Protocol (LSP).

> `locate(acontinent,continents,1;position;'al')`... I may be one of a very small minority that will ever care about this ;-)

I don't think you're in a minority.  I have lots of older code with that form of `Locate`, and I bet a lot of other people do too.

**Comment by itsxallwater** [comment]
Sorry, we are already using a language server. I was just suggesting that we are due to update ours to catch up to what Microsoft is currently recommending in their sample.

Regarding that locate syntax, we used that heavily in D3 at my old shop so you're definitely not alone.

**Comment by kpowick** [comment]
> Sorry, we are already using a language server.

LoL.  Shows how much I still don't know about this project.  Oh well, learning more each day.

**Comment by kpowick** [comment]
I've pushed a [commit](https://github.com/mvextensions/mvbasic/commit/f2d9533161ac212a652e6d31645d732093e14d49) into `develop` that uses the approach of replacing parenthesis and quoted strings with empty ones before linting.  The focus was to help with this issue -- code splitting accuracy on semicolons found within parenthesis.

It seems to work well. I tested it on a lot of my own codebase, test BP files in the project, and Jan's monster program.

I've also remove some repetitive/unnecessary Trim() and RegEx.Test statements, which have improved performance.

Please test against your own code, and let me know if you find any corner cases.

**Comment by ianmcgowan** [comment]
Nice!  Trying it out now.  With strings and parens emptied out it seems
like the only semi-colons left will be statement delimiters.  If that's
true, the loop char-by-char to split the line would be more efficient with
just line.split(';')? I'll give it a shot..

**Comment by kpowick** [comment]
Great.  I've pushed a RegEx cleanup to `develop` based on how lines are being "stripped down" before further linter processing. 

It seems to work well, but if the linter ever gets more sophisticated, such as verifying not only keywords but parameters too, we'll have to rethink a lot of this.  One step at a time though, right? 😀

**Comment by ianmcgowan** [comment]
Kevin, that seems to be working nicely, thanks!  I changed how the line is being split into statements - now there are no extra semi-colons, we can just use split and it's simpler/faster...

**Comment by kpowick** [comment]
I've noticed a small problem with my approach to "cleaning up" code lines before analyzing them. i.e. Replacing quoted strings, parens, extra spaces, etc.  Since the length of the original line of text is changed, it throws off the positioning of the red "error squiggle" displayed by intellisense.

I've got a fix that I plan to push later today.
